/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getHealthcheck_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ProjectsController_findAll_v1"];
    put?: never;
    post: operations["ProjectsController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ProjectsController_findOne_v1"];
    put: operations["ProjectsController_update_v1"];
    post?: never;
    delete: operations["ProjectsController_remove_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{projectId}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["TasksController_findAllByProject_v1"];
    put?: never;
    post: operations["TasksController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{projectId}/tasks/{taskId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["TasksController_findOne_v1"];
    put: operations["TasksController_update_v1"];
    post?: never;
    delete: operations["TasksController_remove_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{projectId}/tasks/{taskId}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["CommentsController_findAllByTask_v1"];
    put?: never;
    post: operations["CommentsController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{projectId}/tasks/{taskId}/comments/{commentId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["CommentsController_findOne_v1"];
    put: operations["CommentsController_update_v1"];
    post?: never;
    delete: operations["CommentsController_remove_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_signup_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/signin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_login_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_forgotPassword_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_resetPassword_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AuthController_me_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["AuthController_changePassword_v1"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_findAll_v1"];
    put?: never;
    post: operations["UsersController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_findOne_v1"];
    put: operations["UsersController_update_v1"];
    post?: never;
    delete: operations["UsersController_remove_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/avatar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["UsersController_uploadAvatar_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{projectId}/collaborators": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["MembersController_findAllByProject_v1"];
    put?: never;
    post: operations["MembersController_create_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/projects/{projectId}/collaborators/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["MembersController_update_v1"];
    post?: never;
    delete: operations["MembersController_remove_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ProjectListItemDto: {
      id: string;
      name: string;
      description?: Record<string, never> | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    TaskAssigneeDto: {
      id: string;
      name: string;
      email: string;
      avatar?: Record<string, never> | null;
    };
    ProjectTaskDto: {
      id: string;
      title: string;
      description?: Record<string, never> | null;
      status: string;
      priority: string;
      /** Format: date-time */
      dueDate?: Record<string, never> | null;
      assignee?: components["schemas"]["TaskAssigneeDto"] | null;
    };
    ProjectFullDto: {
      id: string;
      name: string;
      description?: Record<string, never> | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      createdById: string;
      tasks: components["schemas"]["ProjectTaskDto"][];
    };
    ProjectRequestDto: {
      /** @description Project name */
      name: string;
      /** @description Project description */
      description?: string;
    };
    TaskListItemDto: {
      id: string;
      title: string;
      description?: Record<string, never> | null;
      /** @enum {string} */
      status: "TODO" | "IN_PROGRESS" | "DONE";
      /** @enum {string} */
      priority: "LOW" | "MEDIUM" | "HIGH";
      /** Format: date-time */
      dueDate?: Record<string, never> | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      assignee?: components["schemas"]["TaskAssigneeDto"] | null;
    };
    TaskRequestDto: {
      /** @description Task title */
      title: string;
      /** @description Task description */
      description?: string;
      /**
       * @description Task status
       * @default TODO
       * @enum {string}
       */
      status: "TODO" | "IN_PROGRESS" | "DONE";
      /**
       * @description Task priority
       * @default MEDIUM
       * @enum {string}
       */
      priority: "LOW" | "MEDIUM" | "HIGH";
      /** @description Task due date */
      dueDate?: string;
      /** @description Assignee user ID */
      assigneeId?: string;
    };
    TaskCommentUserDto: {
      id: string;
      name: string;
      email: string;
      avatar?: Record<string, never> | null;
    };
    TaskCommentDto: {
      id: string;
      content: string;
      /** Format: date-time */
      createdAt: string;
      user: components["schemas"]["TaskCommentUserDto"];
    };
    TaskFullDto: {
      id: string;
      title: string;
      description?: Record<string, never> | null;
      /** @enum {string} */
      status: "TODO" | "IN_PROGRESS" | "DONE";
      /** @enum {string} */
      priority: "LOW" | "MEDIUM" | "HIGH";
      /** Format: date-time */
      dueDate?: Record<string, never> | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      assignee?: components["schemas"]["TaskAssigneeDto"] | null;
      comments: components["schemas"]["TaskCommentDto"][];
    };
    CommentAuthorDto: {
      id: string;
      name: string;
      email: string;
      avatar?: Record<string, never> | null;
    };
    CommentListItemDto: {
      id: string;
      content: string;
      taskId: string;
      authorId: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      author: components["schemas"]["CommentAuthorDto"];
    };
    CommentRequestDto: {
      /** @description Comment content */
      content: string;
    };
    CommentTaskDto: {
      id: string;
      title: string;
      projectId: string;
    };
    CommentFullDto: {
      id: string;
      content: string;
      taskId: string;
      authorId: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      author: components["schemas"]["CommentAuthorDto"];
      task: components["schemas"]["CommentTaskDto"];
    };
    SignUpDto: {
      /** @description User name */
      name: string;
      /** @description User email */
      email: string;
      /** @description User password */
      password: string;
      /**
       * @description User role
       * @default ADMIN
       * @enum {string}
       */
      role: "USER" | "ADMIN";
    };
    LoginDto: {
      /** @description User email */
      email: string;
      /** @description User password */
      password: string;
    };
    ForgotPasswordDto: {
      /** @description User email */
      email: string;
    };
    ResetPasswordDto: {
      /** @description Reset token */
      token: string;
      /** @description New password */
      newPassword: string;
    };
    ChangePasswordDto: {
      /** @description Current password */
      currentPassword: string;
      /** @description New password */
      newPassword: string;
    };
    UserListItemDto: {
      id: string;
      name: string;
      email: string;
      avatar?: Record<string, never> | null;
      /** @enum {string} */
      role: "USER" | "ADMIN";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserProjectDto: {
      id: string;
      name: string;
      description?: Record<string, never> | null;
    };
    UserTaskDto: {
      id: string;
      title: string;
      status: string;
    };
    UserCommentDto: {
      id: string;
      content: string;
      /** Format: date-time */
      createdAt: string;
    };
    UserCollaborationProjectDto: {
      id: string;
      name: string;
    };
    UserCollaborationDto: {
      id: string;
      project: components["schemas"]["UserCollaborationProjectDto"];
    };
    UserFullDto: {
      id: string;
      name: string;
      email: string;
      avatar?: Record<string, never> | null;
      /** @enum {string} */
      role: "USER" | "ADMIN";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      createdProjects: components["schemas"]["UserProjectDto"][];
      tasksAssigned: components["schemas"]["UserTaskDto"][];
      comments: components["schemas"]["UserCommentDto"][];
      collaborations: components["schemas"]["UserCollaborationDto"][];
    };
    CreateUserDto: {
      /** @description User name */
      name: string;
      /** @description User email */
      email: string;
      /** @description User password */
      password: string;
      /**
       * @description User role
       * @default ADMIN
       * @enum {string}
       */
      role: "USER" | "ADMIN";
    };
    UpdateUserDto: {
      /** @description User name */
      name?: string;
      /** @description User email */
      email?: string;
      /** @description User avatar */
      avatar?: string;
      /**
       * @description User role
       * @enum {string}
       */
      role?: "USER" | "ADMIN";
    };
    MemberUserDto: {
      id: string;
      name: string;
      email: string;
      avatar?: Record<string, never> | null;
      role: string;
    };
    MemberListItemDto: {
      id: string;
      /** @enum {string} */
      role: "VIEWER" | "EDITOR" | "OWNER";
      projectId: string;
      userId: string;
      /** Format: date-time */
      createdAt: string;
      user: components["schemas"]["MemberUserDto"];
    };
    AddMemberDto: {
      /** @description User ID to add as member */
      userId: string;
      /**
       * @description Member role
       * @default EDITOR
       * @enum {string}
       */
      role: "VIEWER" | "EDITOR" | "OWNER";
    };
    UpdateMemberRoleDto: {
      /**
       * @description New member role
       * @enum {string}
       */
      role: "VIEWER" | "EDITOR" | "OWNER";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHealthcheck_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Healthcheck. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            status?: string;
          };
        };
      };
    };
  };
  ProjectsController_findAll_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data?: components["schemas"]["ProjectListItemDto"][];
            meta?: {
              total?: number;
              lastPage?: number;
              currentPage?: number;
              totalPerPage?: number;
              prevPage?: number | null;
              nextPage?: number | null;
            };
          };
        };
      };
    };
  };
  ProjectsController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectRequestDto"];
      };
    };
    responses: {
      /** @description Project created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFullDto"];
        };
      };
    };
  };
  ProjectsController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get project by ID. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFullDto"];
        };
      };
    };
  };
  ProjectsController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectRequestDto"];
      };
    };
    responses: {
      /** @description Project updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFullDto"];
        };
      };
    };
  };
  ProjectsController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project deleted successfully. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TasksController_findAllByProject_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data?: components["schemas"]["TaskListItemDto"][];
            meta?: {
              total?: number;
              lastPage?: number;
              currentPage?: number;
              totalPerPage?: number;
              prevPage?: number | null;
              nextPage?: number | null;
            };
          };
        };
      };
    };
  };
  TasksController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskRequestDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskListItemDto"];
        };
      };
    };
  };
  TasksController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskFullDto"];
        };
      };
    };
  };
  TasksController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskRequestDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskListItemDto"];
        };
      };
    };
  };
  TasksController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Task deleted successfully. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CommentsController_findAllByTask_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data?: components["schemas"]["CommentListItemDto"][];
            meta?: {
              total?: number;
              lastPage?: number;
              currentPage?: number;
              totalPerPage?: number;
              prevPage?: number | null;
              nextPage?: number | null;
            };
          };
        };
      };
    };
  };
  CommentsController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentRequestDto"];
      };
    };
    responses: {
      /** @description Comment created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentListItemDto"];
        };
      };
    };
  };
  CommentsController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskId: string;
        commentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get comment by ID. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentFullDto"];
        };
      };
    };
  };
  CommentsController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskId: string;
        commentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentRequestDto"];
      };
    };
    responses: {
      /** @description Comment updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentListItemDto"];
        };
      };
    };
  };
  CommentsController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        taskId: string;
        commentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Comment deleted successfully. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_signup_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_forgotPassword_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_resetPassword_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordDto"];
      };
    };
    responses: {
      /** @description Password reset successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid or expired token. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_changePassword_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDto"];
      };
    };
    responses: {
      /** @description Password changed successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Current password is incorrect. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_findAll_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data?: components["schemas"]["UserListItemDto"][];
            meta?: {
              total?: number;
              lastPage?: number;
              currentPage?: number;
              totalPerPage?: number;
              prevPage?: number | null;
              nextPage?: number | null;
            };
          };
        };
      };
    };
  };
  UsersController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      /** @description User created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserListItemDto"];
        };
      };
    };
  };
  UsersController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get user by ID. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserFullDto"];
        };
      };
    };
  };
  UsersController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserDto"];
      };
    };
    responses: {
      /** @description User updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserListItemDto"];
        };
      };
    };
  };
  UsersController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User deleted successfully. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_uploadAvatar_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file?: string;
        };
      };
    };
    responses: {
      /** @description User avatar uploaded successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserFullDto"];
        };
      };
    };
  };
  MembersController_findAllByProject_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data?: components["schemas"]["MemberListItemDto"][];
            meta?: {
              total?: number;
              lastPage?: number;
              currentPage?: number;
              totalPerPage?: number;
              prevPage?: number | null;
              nextPage?: number | null;
            };
          };
        };
      };
    };
  };
  MembersController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddMemberDto"];
      };
    };
    responses: {
      /** @description Member added successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberListItemDto"];
        };
      };
    };
  };
  MembersController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMemberRoleDto"];
      };
    };
    responses: {
      /** @description Member role updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberListItemDto"];
        };
      };
    };
  };
  MembersController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Member removed successfully. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
