/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHealthCheck_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectsController_findAll_v1"];
        put?: never;
        post: operations["ProjectsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectsController_findById_v1"];
        put: operations["ProjectsController_update_v1"];
        post?: never;
        delete: operations["ProjectsController_delete_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_findAll_v1"];
        put?: never;
        post: operations["ChatController_enqueue_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/ws-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChatController_createWsTicket_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_findById_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TasksController_findAllByProjectId_v1"];
        put?: never;
        post: operations["TasksController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TasksController_findById_v1"];
        put: operations["TasksController_update_v1"];
        post?: never;
        delete: operations["TasksController_delete_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/tasks/{taskId}/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TasksController_findSubtasks_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TagsController_findAll_v1"];
        put?: never;
        post: operations["TagsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["TagsController_delete_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findAll_v1"];
        put?: never;
        post: operations["UsersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findById_v1"];
        put: operations["UsersController_update_v1"];
        post?: never;
        delete: operations["UsersController_delete_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UsersController_uploadAvatar_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/collaborators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CollaboratorsController_findAllByProject_v1"];
        put?: never;
        post: operations["CollaboratorsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/collaborators/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["CollaboratorsController_update_v1"];
        post?: never;
        delete: operations["CollaboratorsController_delete_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/tasks/{taskId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CommentsController_findAllByTaskId_v1"];
        put?: never;
        post: operations["CommentsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/tasks/{taskId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CommentsController_findById_v1"];
        put: operations["CommentsController_update_v1"];
        post?: never;
        delete: operations["CommentsController_delete_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signup_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signin_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_forgotPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resetPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_getMe_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["McpController_processRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["McpController_getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/execute-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["McpController_executeAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_getSummary_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProjectItemListDTO: {
            id: string;
            name: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description Role of the current user within the project
             * @enum {string}
             */
            role: "VIEWER" | "EDITOR" | "OWNER";
            /** @description Number of members (collaborators) in the project */
            membersCount: number;
        };
        TaskCommentUserDTO: {
            id: string;
            name: string;
            email: string;
            avatar?: Record<string, never> | null;
        };
        TaskCommentDTO: {
            id: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
            author: components["schemas"]["TaskCommentUserDTO"];
        };
        TagDTO: {
            id: string;
            name: string;
            /** @description Color token: brand | emerald | amber | rose | violet | cyan | muted */
            color: string;
        };
        TaskAssineeDTO: {
            id: string;
            name: string;
            email: string;
            avatar?: Record<string, never> | null;
        };
        SubtaskProgressDTO: {
            /** @description Subtarefas com status DONE */
            done: number;
            /** @description Total de subtarefas */
            total: number;
        };
        ProjectTaskDTO: {
            id: string;
            title: string;
            description: string | null;
            /**
             * @default TODO
             */
            status: string;
            /**
             * @default MEDIUM
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH";
            /** @description Fractional index key for ordering within the status column */
            order: string;
            /** Format: date-time */
            dueDate: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            comments: components["schemas"]["TaskCommentDTO"][];
            tags: components["schemas"]["TagDTO"][];
            assignee?: components["schemas"]["TaskAssineeDTO"] | null;
            /** @description Sempre null aqui: o board lista apenas tarefas top-level. */
            parentId?: string | null;
            /** @description Progresso das subtarefas (done/total) para o indicador "3/5" no card. */
            subtaskProgress: components["schemas"]["SubtaskProgressDTO"];
        };
        CollaboratorUserDTO: {
            id: string;
            name: string;
            email: string;
            avatar: string | null;
        };
        CollaboratorItemListDTO: {
            id: string;
            /** @enum {string} */
            role: "VIEWER" | "EDITOR" | "OWNER";
            projectId: string;
            userId: string;
            /** Format: date-time */
            createAt: string;
            user: components["schemas"]["CollaboratorUserDTO"];
        };
        ProjectStatusDTO: {
            id: string;
            name: string;
            value: string;
            order: number;
        };
        ProjectFullDTO: {
            id: string;
            name: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description Role of the current user within the project
             * @enum {string}
             */
            role: "VIEWER" | "EDITOR" | "OWNER";
            /** @description Number of members (collaborators) in the project */
            membersCount: number;
            tasks: components["schemas"]["ProjectTaskDTO"][];
            collaborators: components["schemas"]["CollaboratorItemListDTO"][];
            statuses: components["schemas"]["ProjectStatusDTO"][];
        };
        ProjectDTO: {
            /** @description Project name */
            name: string;
            /** @description Project description */
            description?: string;
            statuses?: { id?: string; name: string; value: string }[];
        };
        ChatMessageDTO: {
            /** @description Message content */
            message: string;
        };
        ChatMessageResponseDTO: {
            id: string;
            userId: string;
            content: string;
            response: Record<string, never> | null;
            /** @enum {string} */
            status: "QUEUED" | "PROCESSING" | "DELIVERED" | "FAILED";
            filters: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WsTicketResponseDTO: {
            /** @description Short-lived ticket for the WebSocket handshake */
            ticket: string;
            /** @description Ticket lifetime in seconds */
            expiresIn: number;
        };
        TaskItemListDTO: {
            id: string;
            title: string;
            description?: Record<string, never> | null;
            status: string;
            /** @enum {string} */
            priority: "LOW" | "MEDIUM" | "HIGH";
            /** @description Fractional index key for ordering within the status column */
            order: string;
            /** @description Id da tarefa-pai (null para tarefas top-level). */
            parentId?: string | null;
            /** Format: date-time */
            dueDate?: Record<string, never> | null;
            tags: components["schemas"]["TagDTO"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            assignee?: components["schemas"]["TaskAssineeDTO"] | null;
            /** @description Progresso das subtarefas. Presente apenas em tarefas top-level; ausente/omitido para subtarefas (que não têm filhas). */
            subtaskProgress?: components["schemas"]["SubtaskProgressDTO"];
        };
        TasksRequestDTO: {
            /** @description Task title */
            title: string;
            /** @description Task description */
            description: string;
            /**
             * @description Task status
             * @default TODO
             */
            status: string;
            /**
             * @description Task priority
             * @default MEDIUM
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH";
            /** @description Task due date */
            dueDate?: string;
            /** @description Assinee User Id */
            assigneeId?: string;
            /** @description Tag names to attach to the task. Existing tags (by name, for the current user) are reused; unknown names are created automatically with an auto-assigned color. Omit to leave tags unchanged on update. */
            tags?: string[];
            /** @description Target index (0-based) within the status column. Ignored on create (a new task always goes to the top). On update, moves the task to this position; the server computes the fractional `order` key. */
            position?: number;
            /** @description Id da tarefa-pai. Quando informado, esta task é criada como subtarefa. Regra de 1 nível: a tarefa-pai não pode ser, ela mesma, uma subtarefa. A subtarefa herda o projeto do pai. Omita para uma tarefa top-level. */
            parentId?: string | null;
        };
        TaskFullDTO: {
            id: string;
            title: string;
            description?: Record<string, never> | null;
            status: string;
            /** @enum {string} */
            priority: "LOW" | "MEDIUM" | "HIGH";
            /** @description Fractional index key for ordering within the status column */
            order: string;
            /** @description Id da tarefa-pai (null para tarefas top-level). */
            parentId?: string | null;
            /** Format: date-time */
            dueDate?: Record<string, never> | null;
            tags: components["schemas"]["TagDTO"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            assignee?: components["schemas"]["TaskAssineeDTO"] | null;
            comments: components["schemas"]["TaskCommentDTO"][];
            /** @description Subtarefas desta tarefa, ordenadas por `order`. Vazio para subtarefas. */
            subtasks: components["schemas"]["TaskItemListDTO"][];
            /** @description Progresso das subtarefas (done/total). Ausente para subtarefas. */
            subtaskProgress?: components["schemas"]["SubtaskProgressDTO"];
        };
        CreateTagDTO: {
            /** @description Tag name (unique per user) */
            name: string;
            /**
             * @description Color token. If omitted, a color is auto-assigned from the name.
             * @enum {string}
             */
            color?: "brand" | "emerald" | "amber" | "rose" | "violet" | "cyan" | "muted";
        };
        UserItemListDTO: {
            id: string;
            name: string;
            email: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UsersDTO: {
            /** @description User name */
            name: string;
            /** @description User email */
            email: string;
            /** @description User password */
            password: string;
            /**
             * @description User role
             * @default ADMIN
             * @enum {string}
             */
            role: "USER" | "ADMIN";
        };
        UserProjectDTO: {
            id: string;
            name: string;
            description?: string | null;
        };
        UserFullDTO: {
            id: string;
            name: string;
            email: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createProjects: components["schemas"]["UserProjectDTO"][];
        };
        UpdateUsersDTO: {
            /** @description User name */
            name?: string;
            /**
             * @description User role
             * @default ADMIN
             * @enum {string}
             */
            role: "USER" | "ADMIN";
        };
        AddCollaboratorDTO: {
            /** @description User ID to add as collaborator */
            email: string;
            /**
             * @description Collaborator role
             * @default EDITOR
             * @enum {string}
             */
            role: "VIEWER" | "EDITOR" | "OWNER";
        };
        UpdateCollaboratorDTO: {
            /**
             * @description New collaborator role
             * @enum {string}
             */
            role: "VIEWER" | "EDITOR" | "OWNER";
        };
        AddCommentDTO: {
            /** @description Task comment */
            content: string;
        };
        CommentAuthorDTO: {
            id: string;
            name: string;
            email: string;
            avatar: string | null;
        };
        CommentItemListDTO: {
            id: string;
            content: string;
            taskId: string;
            authorId: string;
            /** Format: date-time */
            createAt: string;
            /** Format: date-time */
            updatedAt: string;
            author: components["schemas"]["CommentAuthorDTO"];
        };
        CommentTaskDTO: {
            id: string;
            title: string;
            projectId: string;
        };
        CommentFullDTO: {
            id: string;
            content: string;
            taskId: string;
            authorId: string;
            /** Format: date-time */
            createAt: string;
            /** Format: date-time */
            updatedAt: string;
            author: components["schemas"]["CommentAuthorDTO"];
            task: components["schemas"]["CommentTaskDTO"];
        };
        UpdateCommentDTO: {
            /** @description Task comment */
            content: string;
        };
        SignUpDTO: {
            /** @description User name */
            name: string;
            /** @description User email */
            email: string;
            /** @description User password */
            password: string;
        };
        SignInDTO: {
            /** @description User email */
            email: string;
            /** @description User password */
            password: string;
        };
        ForgotPasswordDTO: {
            /** @description User email */
            email: string;
        };
        ResetPasswordDTO: {
            /** @description Reset Token */
            token: string;
            /** @description New password */
            newPassword: string;
        };
        DashboardStatsDTO: {
            /** @description Tasks with status TODO or IN_PROGRESS */
            activeTasks: number;
            /** @description Tasks completed (DONE) in the last 7 days */
            completedLast7Days: number;
            /** @description Tasks with status IN_PROGRESS */
            inProgress: number;
        };
        DashboardProjectTotalAndDoneDTO: {
            id: string;
            name: string;
            totalTasks: number;
            doneTasks: number;
        };
        DashboardProjectDTO: {
            id: string;
            name: string;
        };
        DashboardTaskDTO: {
            id: string;
            title: string;
            project: components["schemas"]["DashboardProjectDTO"];
            /** Format: date-time */
            dueDate: Record<string, never> | null;
            /** @enum {string} */
            priority: "LOW" | "MEDIUM" | "HIGH";
            status: string;
        };
        DashboardSummaryDTO: {
            stats: components["schemas"]["DashboardStatsDTO"];
            recentProjects: components["schemas"]["DashboardProjectTotalAndDoneDTO"][];
            upcomingTasks: components["schemas"]["DashboardTaskDTO"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealthCheck_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HealthCheck */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
        };
    };
    ProjectsController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ProjectItemListDTO"][];
                        meta?: {
                            total?: number;
                            lastPage?: number;
                            currentPage?: number;
                            totalPerPage?: number;
                            prevPage?: number | null;
                            nextPage?: number | null;
                        };
                    };
                };
            };
        };
    };
    ProjectsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectItemListDTO"];
                };
            };
        };
    };
    ProjectsController_findById_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFullDTO"];
                };
            };
        };
    };
    ProjectsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDTO"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectItemListDTO"];
                };
            };
        };
    };
    ProjectsController_delete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_findAll_v1: {
        parameters: {
            query?: {
                /** @description Number of last messages to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponseDTO"][];
                };
            };
        };
    };
    ChatController_enqueue_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponseDTO"];
                };
            };
        };
    };
    ChatController_createWsTicket_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsTicketResponseDTO"];
                };
            };
        };
    };
    ChatController_findById_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponseDTO"];
                };
            };
        };
    };
    TasksController_findAllByProjectId_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TaskItemListDTO"][];
                        meta?: {
                            total?: number;
                            lastPage?: number;
                            currentPage?: number;
                            totalPerPage?: number;
                            prevPage?: number | null;
                            nextPage?: number | null;
                        };
                    };
                };
            };
        };
    };
    TasksController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TasksRequestDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemListDTO"];
                };
            };
        };
    };
    TasksController_findById_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskFullDTO"];
                };
            };
        };
    };
    TasksController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TasksRequestDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemListDTO"];
                };
            };
        };
    };
    TasksController_delete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findSubtasks_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemListDTO"][];
                };
            };
        };
    };
    TagsController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDTO"][];
                };
            };
        };
    };
    TagsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDTO"];
                };
            };
        };
    };
    TagsController_delete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["UserItemListDTO"][];
                        meta?: {
                            total?: number;
                            lastPage?: number;
                            currentPage?: number;
                            totalPerPage?: number;
                            prevPage?: number | null;
                            nextPage?: number | null;
                        };
                    };
                };
            };
        };
    };
    UsersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsersDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserItemListDTO"];
                };
            };
        };
    };
    UsersController_findById_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFullDTO"];
                };
            };
        };
    };
    UsersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUsersDTO"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserItemListDTO"];
                };
            };
        };
    };
    UsersController_delete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_uploadAvatar_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description User avatar uploaded sucessfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserItemListDTO"];
                };
            };
            /** @description Invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CollaboratorsController_findAllByProject_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CollaboratorItemListDTO"][];
                        meta?: {
                            total?: number;
                            lastPage?: number;
                            currentPage?: number;
                            totalPerPage?: number;
                            prevPage?: number | null;
                            nextPage?: number | null;
                        };
                    };
                };
            };
        };
    };
    CollaboratorsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCollaboratorDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollaboratorItemListDTO"];
                };
            };
        };
    };
    CollaboratorsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCollaboratorDTO"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollaboratorItemListDTO"];
                };
            };
        };
    };
    CollaboratorsController_delete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_findAllByTaskId_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CommentItemListDTO"][];
                        meta?: {
                            total?: number;
                            lastPage?: number;
                            currentPage?: number;
                            totalPerPage?: number;
                            prevPage?: number | null;
                            nextPage?: number | null;
                        };
                    };
                };
            };
        };
    };
    CommentsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCommentDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentItemListDTO"];
                };
            };
        };
    };
    CommentsController_findById_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentFullDTO"];
                };
            };
        };
    };
    CommentsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentItemListDTO"];
                };
            };
        };
    };
    CommentsController_delete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signup_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserItemListDTO"];
                };
            };
        };
    };
    AuthController_signin_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpController_processRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpController_getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpController_executeAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getSummary_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryDTO"];
                };
            };
        };
    };
}
